name = "NPBCOVID"
version = "0.1.0"
license = "license"
author = "Yao Gongzheng"
maintainer = "jane.doe@example.com"
copyright = "Copyright 2023, Yao Gongzheng"
[build]
auto-executables = false
auto-tests = true
auto-examples = true
link = ["openblas"]

[install]
library = false

[library]
include-dir = ["src"]

[[executable]]
name = "NPBCOVID"
source-dir = "app"
main = "main.f90"


[dependencies]
functional.git = "https://github.com/wavebitscientific/functional-fortran"
stdlib = { git="https://github.com/fortran-lang/stdlib", branch="stdlib-fpm" }
fortran-csv-module = { git="https://github.com/jacobwilliams/fortran-csv-module.git" }